// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdbHxfsmRRILEtuwUsaSg00vyOGU1oIS8',
    appId: '1:1036298061520:web:75925dffabe12cfc2240d5',
    messagingSenderId: '1036298061520',
    projectId: 'foodapp-4bfb7',
    authDomain: 'foodapp-4bfb7.firebaseapp.com',
    storageBucket: 'foodapp-4bfb7.firebasestorage.app',
    measurementId: 'G-4JX5GBWFHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcRypiCwON3DKtT1aEis6kML-3QC66KX4',
    appId: '1:1036298061520:android:5b7a605367ecb90f2240d5',
    messagingSenderId: '1036298061520',
    projectId: 'foodapp-4bfb7',
    storageBucket: 'foodapp-4bfb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-1SofDuheq5Qr94e8iD7dCj13vRuv1kQ',
    appId: '1:1036298061520:ios:4774338d1d82692b2240d5',
    messagingSenderId: '1036298061520',
    projectId: 'foodapp-4bfb7',
    storageBucket: 'foodapp-4bfb7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAppnexts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-1SofDuheq5Qr94e8iD7dCj13vRuv1kQ',
    appId: '1:1036298061520:ios:4774338d1d82692b2240d5',
    messagingSenderId: '1036298061520',
    projectId: 'foodapp-4bfb7',
    storageBucket: 'foodapp-4bfb7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAppnexts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdbHxfsmRRILEtuwUsaSg00vyOGU1oIS8',
    appId: '1:1036298061520:web:cf89bbb7f3ac9ef52240d5',
    messagingSenderId: '1036298061520',
    projectId: 'foodapp-4bfb7',
    authDomain: 'foodapp-4bfb7.firebaseapp.com',
    storageBucket: 'foodapp-4bfb7.firebasestorage.app',
    measurementId: 'G-7LWM1EN85B',
  );
}
